name: C/C++ CI

on:
  push:
      branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        git clone https://github.com/alex85k/sqlite3-cmake
        cd sqlite3-cmake
        cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=d:/libs
        nmake install

    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake -G "Unix Makefiles" ..

    - name: build
      run: |
        cd Cpp/build
        make
