name: build

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: configure-build
      run: |
        cd win
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd win/build
        cmake --build . -- -j $(nproc)
        
    - name: run
      run: |
        cd win/build
        ./coolok
        
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: configure-build
        run: |
          cd win
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
          
      - name: build
        run: |
          cd win/build
          mingw32-make.exe
          
      - name: run
        run: |
          cd win/build
          . .\coolok.exe
        
        
