name: build

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: configure-build
      run: |
        cd win
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd win/build
        cmake --build . -- -j $(nproc)
        
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: configure-build
        run: |
          cd win
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
        
        
