name: C/C++ CI

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cd Cpp && mkdir build && cd build && cmake ..
    - name: build
      run: make
  
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: make
  
