name: C/C++ CI

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        cd /usr/bin/
        ls
    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..
    - name: build
      run: |
        cd Cpp/build
        make
  
