name: C/C++ CI

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 50
        sudo update-alternatives --set gcc "/usr/bin/gcc-9"
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 50
        sudo update-alternatives --set g++ "/usr/bin/g++-9"
        sudo apt-get install libsqlite3-dev
        sudo apt-get update
    - name: build-tbb
      run: |
        sudo apt-get build-dep libtbb-dev
        git clone https://github.com/intel/tbb
        cd tbb
        git checkout 2019_U9
        make -j `nproc`
        TBB="$(pwd)"
        TBB_RELEASE="${TBB}/build/linux_intel64_gcc_cc7.4.0_libc2.27_kernel4.15.0_release"
    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..
    - name: build
      run: |
        cd Cpp/build
        make

