name: C/C++ CI

on:
  push:
      branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        git clone https://github.com/sayansil/sqlite-amalgamation-3310100
        cd sqlite-amalgamation-3310100
        gcc -shared sqlite3.c -o sqlite3.dll

    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake cmake -G "Unix Makefiles" ..

    - name: build
      run: |
        cd Cpp/build
        make
