name: build

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: configure-build
      run: |
        cd win
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd win/build
        cmake --build . -- -j $(nproc)
        
    - name: run
      run: |
        cd win/build
        ./coolok
        
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
        
      - name: configure-build
        run: |
          cd "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\vc\\Auxiliary\\build"
          . .\vcvarsall.bat x64
          cd "D:\a\test_cpp_actions\test_cpp_actions\win"
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -DCMAKE_C_COMPILER="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.27.29110\\bin\\Hostx64\\x64\\cl.exe" -DCMAKE_CXX_COMPILER="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.27.29110\\bin\\Hostx64\\x64\\cl.exe" ..
          
      - name: build
        run: |
          cd win/build
          ninja
          
      - name: run
        run: |
          cd win/build
          . .\coolok.exe
        
        
