name: C/C++ CI

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 50
        sudo update-alternatives --set gcc "/usr/bin/gcc-9"
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 50
        sudo update-alternatives --set g++ "/usr/bin/g++-9"
        sudo apt-get install libtbb-dev
    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..
    - name: build
      run: |
        cd Cpp/build
        make
  
