name: C/C++ CI

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo update-alternatives --set gcc "/usr/bin/gcc-9"
        sudo update-alternatives --set g++ "/usr/bin/g++-9"
        sudo apt install libsqlite3-dev
        echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
        sudo apt update
        sudo apt install libtbb-dev
        dpkg -L libtbb-dev
    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..
    - name: build
      run: |
        cd Cpp/build
        make
  
